config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  authenticated :user do
    root to: 'posts#index'
  end
  unauthenticated :user do
    root to: 'static_pages#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :remember_me])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = 'Sharebit'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/_footer.html.erb
<ul class="list-inline">
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
  <li><%= link_to 'Log In', new_user_session_path %></li>
  <li><%= link_to 'About', '#' %></li>
  <li><%= link_to 'Help', '#' %></li>
  <li><%= link_to 'Github', 'https://github.com/edwincarbajal/socialnetwork' %></li>
</ul>
<p class="text-muted">Sharebit <span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span> 2017</p>
<p class="text-center">
  Made with <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> by <a href="http://edwincarbajal.com" target="_blank">Edwin</a>.
</p>

app/views/static_pages/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'sharebit', root_url, class: 'navbar-brand' %>
    </div>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'navbar-form navbar-right form-inline' }) do |f| %>
      <div class="form-group">
        <%#= f.label :email %>
        <div>Email</div>
        <%= f.email_field :email, class: 'form-control', autofocus: true, placeholder: 'email@example.com' %>
      </div>
      <div class="form-group">
        <%#= f.label :password %>
        <div>Password</div>
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off', placeholder: 'password' %>
        <div>
          <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
            <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
          <% end -%>
        </div>
      </div>
      <%= f.submit 'Log in', class: 'btn btn-primary' %>
    <% end %>
  </div>
</nav>

app/views/static_pages/_sign_up_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <% if resource.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <%= resource.errors.full_messages.first %>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    </div>
  <% end %>
  <div class="form-group">
    <div class="row">
      <div class="col-xs-8">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', autofocus: true, placeholder: 'Full name' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-xs-8">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'email@example.com' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-xs-8">
        <%= f.label :password %>
        <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
        <% end %><br>
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off', placeholder: 'password' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="col-xs-8">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off', placeholder: 'password confirmation' %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit 'Sign up', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/static_pages/index.html.erb
<%= provide(:title, 'Log In or Sign Up') %>
<div class="container-fluid">
  <div class="row">
    <%= render 'navbar' %>
  </div>

  <div class="row">
    <div class="col-md-7 text-center">
      <h1><strong>Connect with friends and the<br>world around you on Sharebit.</strong></h1>
      <p class="lead">Sharebit is social networking app written using<br> React and Ruby on Rails.You can checkout how it was developed<br> and also the source code on <a href="https://github.com/edwincarbajal/socialnetwork">Github</a>.</p>
      <p>
        <button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span> Star it</button>
        <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Fork it</button>
      </p>
    </div>

    <div class="col-md-5">
      <h1><strong>Sign Up</strong></h1>
      <p class="small">It's free and always will be.</p>
      <%= render 'sign_up_form' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="navbar-static-bottom">
        <div class="container">
          <%= render 'footer' %>
        </div>
      </div>
    </div>
  </div>
</div>